import fs from "fs";
import glob from "fast-glob";

async function start() {
  const HTMLFiles = await glob(["./**/*.html"], {
    ignore: ["./index.html", "**/node_modules/**"],
  });
  HTMLFiles.sort();
  const result = HTMLFiles.map((filepath) => {
    const arr = filepath.split("/");
    if (arr[0] === "react-examples") {
      return `<li><a href="${filepath}">react-examples/${arr[2]}</a></li>`;
    }
    return `<li><a href="${filepath}">${
      arr[1].startsWith("index.") ? arr[0] : filepath
    }</a></li>`;
  }).join("\n");

  const htmlTemplate = `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="index.css" />
    <title>ui</title>
  </head>
  <body>
    <!-- generated by ./index.mjs -->
    <h1>ui</h1>
    <div class="toggle-view"> 
    <button id="grid-btn">Grid View</button>
    <button id="list-btn">List View</button>
      <button id="dark-mode-btn">Dark Mode</button>
    </div>
    <ul id="menu" class="grid-view">
      ${result}
    </ul>
    <script>
      const gridBtn = document.getElementById('grid-btn');
      const listBtn = document.getElementById('list-btn');
      const nightModeBtn = document.getElementById('dark-mode-btn');
      const menu = document.getElementById('menu');

      gridBtn.addEventListener('click', () => {
        if (!menu.classList.contains('grid-view')) {
          menu.classList.remove('list-view');
          menu.classList.add('grid-view');
        }
      });

      listBtn.addEventListener('click', () => {
        if (!menu.classList.contains('list-view')) {
          menu.classList.remove('grid-view');
          menu.classList.add('list-view');
        }
      });

      nightModeBtn.addEventListener('click', () => {
        document.body.classList.toggle('night-mode');
      });
    </script>
  </body>
  </html>
  `;

  fs.writeFile("./index.html", htmlTemplate, (err) => {});
}

start();
